services:
  - type: web
    name: agenda-isere
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
